TMA-735 Failed To Consume Event Message to S3
alphagov/di-txma-audit pull request #339
Opened 2022-11-10 19:29 UTC by abdulkalam-govuk

Code clean up done as JsonPath made it simpler.

2022-11-11 12:44 UTC, zaydgds requested changes

2022-11-14 08:48 UTC, abdulkalam-govuk commented on event-processing/lambda/models/redacted-event.ts
> +        if (JSONPath({
DONE

2022-11-14 08:48 UTC, abdulkalam-govuk commented on event-processing/lambda/models/redacted-event.ts
> +        if (JSONPath({
DONE

2022-11-14 08:48 UTC, abdulkalam-govuk commented on event-processing/lambda/models/redacted-event.ts
>  export class RedactedAuditEventUserMessage {
Remove the unused

2022-11-14 08:49 UTC, abdulkalam-govuk commented on event-processing/lambda/services/redacted-service.ts
>  export class RedactedService {
Rename DONE

2022-11-14 11:14 UTC, zaydgds approved these changes

2022-11-14 11:43 UTC, merged